### ISSUE TITLE
[Bug] Creation of Satsdice not possible

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/satsdice#6]
Example from two different lnbitses v0.10.9 with Satsdice v0.1.0

![photo_2023-09-22_20-19-32](https://github.com/lnbits/satsdice/assets/63317640/caa43085-e16b-4dfc-862e-20c3d579a87e)

![image_2023-09-22_16-12-24](https://github.com/lnbits/satsdice/assets/63317640/07f141ed-7695-4a28-bd71-96548f5fdee2)

**Comment by talvasconcelos** [comment]
This has been fixed!

**Comment by arbadacarbaYK** [comment]
yeah its from september :P youre welcome :P
